### PR TITLE
First pass at a YAML generator.

### PR DESCRIPTION
**Pull request by dieterrosch**
First pass at YAML generator. 
Also fixes annoying bug where a broken dependency library causes the help not to be printed.

### CODE REVIEW

**Comment by ZoranPavlovic** [comment]
@dieterrosch  - Would be really curious to see a sample of the outputted YAML?

**Comment by dieterrosch** [comment]
> @dieterrosch - Would be really curious to see a sample of the outputted YAML?

Will add an example.

**Comment by dieterrosch** [comment]
@ZoranPavlovic Example of [ContingencyStatus.si](https://github.com/SI-Gen/jportal2/blob/yaml-generator/src/main/resources/example_si_files/ContingencyStatus.si):

```yaml
&id002 !!bbd.jportal2.Database
flags: []
generatedOutputFiles:
- fileGroups:
  - &id001 {fileGroupName: Java}
  - *id001
  generatorName: JavaJCCode
- fileGroups:
  - {fileGroupName: sh}
  - {fileGroupName: cpp}
  generatorName: MSSqlCCode
- fileGroups:
  - {fileGroupName: py}
  generatorName: PythonTreeCode
- fileGroups:
  - {fileGroupName: sh}
  - {fileGroupName: cpp}
  - {fileGroupName: _snips.h}
  generatorName: CliCCode
- fileGroups:
  - {fileGroupName: ii}
  - {fileGroupName: cs}
  generatorName: IdlCode
- fileGroups: []
  generatorName: OracleDDL
- fileGroups:
  - {fileGroupName: sql}
  - {fileGroupName: _data.sql}
  generatorName: Db2DDL
- fileGroups:
  - {fileGroupName: sql}
  generatorName: MSSqlDDL
- fileGroups:
  - {fileGroupName: cs}
  generatorName: CSNetCode
- fileGroups:
  - {fileGroupName: sh}
  - {fileGroupName: cpp}
  generatorName: CliCCode2
imports: []
name: testDatabase
output: ContingencyStatus
packageName: co.za.entities
password: ''
schema: ''
sequences: []
server: PostgeSQL95
tables:
- &id007
  alias: ''
  allUsers: []
  check: ''
  comments: []
  consts: []
  database: *id002
  fields:
  - &id003
    alias: ''
    bindPos: 0
    checkValue: ''
    comments: []
    defaultValue: ''
    definePos: 0
    enumLink: ''
    enumType: null
    enums: []
    isCalc: false
    isExtStd: false
    isExtStdOut: false
    isIn: false
    isLiteral: false
    isNull: false
    isOut: false
    isPrimaryKey: true
    isSequence: false
    length: 4
    literalName: ''
    name: ID
    precision: 0
    scale: 0
    type: 11
    valueList: []
  - &id004
    alias: ''
    bindPos: 0
    checkValue: ''
    comments: []
    defaultValue: ''
    definePos: 0
    enumLink: ''
    enumType: null
    enums: []
    isCalc: false
    isExtStd: false
    isExtStdOut: false
    isIn: false
    isLiteral: false
    isNull: false
    isOut: false
    isPrimaryKey: false
    isSequence: false
    length: 50
    literalName: ''
    name: Description
    precision: 0
    scale: 0
    type: 4
    valueList: []
  - &id005
    alias: ''
    bindPos: 0
    checkValue: ''
    comments: []
    defaultValue: ''
    definePos: 0
    enumLink: ''
    enumType: null
    enums: []
    isCalc: false
    isExtStd: false
    isExtStdOut: false
    isIn: false
    isLiteral: false
    isNull: false
    isOut: false
    isPrimaryKey: false
    isSequence: false
    length: 48
    literalName: ''
    name: UsrID
    precision: 0
    scale: 0
    type: 4
    valueList: []
  - &id006
    alias: ''
    bindPos: 0
    checkValue: ''
    comments: []
    defaultValue: ''
    definePos: 0
    enumLink: ''
    enumType: null
    enums: []
    isCalc: false
    isExtStd: false
    isExtStdOut: false
    isIn: false
    isLiteral: false
    isNull: false
    isOut: false
    isPrimaryKey: false
    isSequence: false
    length: 14
    literalName: ''
    name: TMStamp
    precision: 0
    scale: 0
    type: 18
    valueList: []
  grants: []
  hasAutoTimeStamp: false
  hasBigXML: false
  hasDelete: false
  hasExecute: false
  hasIdentity: false
  hasInsert: false
  hasPrimaryKey: true
  hasSelect: false
  hasSequence: false
  hasSequenceReturning: false
  hasStdProcs: true
  hasTimeStamp: true
  hasUpdate: false
  hasUserStamp: false
  isLiteral: false
  isStoredProc: false
  keys:
  - fields: [ID]
    isPrimary: true
    isUnique: false
    name: PKEY
    options: []
  links: []
  literalName: ''
  name: ContingencyStatus
  options: []
  parameters: []
  procs:
  - comments: []
    dynamicSizes: []
    dynamicStrung: []
    dynamics: []
    extendsStd: false
    fields: []
    from: ''
    hasImage: false
    hasReturning: false
    hasUpdates: false
    inputs:
    - *id003
    - *id004
    - *id005
    - *id006
    isAction: false
    isData: false
    isIdlCode: false
    isInsert: true
    isMultipleInput: false
    isProc: true
    isSProc: false
    isSingle: false
    isSql: true
    isStd: true
    isUpdate: false
    lines:
    - {isVar: false, line: /* PROC .ContingencyStatus.Insert */}
    - {isVar: false, line: insert into ContingencyStatus (}
    - {isVar: false, line: '  ID,'}
    - {isVar: false, line: '  Description,'}
    - {isVar: false, line: '  UsrID,'}
    - {isVar: false, line: '  TMStamp'}
    - {isVar: false, line: ' ) '}
    - {isVar: false, line: ' values ('}
    - {isVar: false, line: '  ?,'}
    - {isVar: false, line: '  ?,'}
    - {isVar: false, line: '  ?,'}
    - {isVar: false, line: '  ?'}
    - {isVar: false, line: ' )'}
    name: Insert
    noRows: 0
    options: []
    orderFields: []
    outputs: []
    placeHolders: []
    start: 17
    table: *id007
    updateFields: []
    useKey: false
    useStd: false
    username: ''
    where: ''
  - comments: []
    dynamicSizes: []
    dynamicStrung: []
    dynamics: []
    extendsStd: false
    fields: []
    from: ''
    hasImage: false
    hasReturning: false
    hasUpdates: false
    inputs:
    - *id003
    isAction: false
    isData: false
    isIdlCode: false
    isInsert: false
    isMultipleInput: false
    isProc: true
    isSProc: false
    isSingle: true
    isSql: true
    isStd: true
    isUpdate: false
    lines:
    - {isVar: false, line: /* PROC .ContingencyStatus.SelectOne */}
    - {isVar: false, line: select}
    - {isVar: false, line: '  Description'}
    - {isVar: false, line: ', UsrID'}
    - {isVar: false, line: ', TMStamp'}
    - {isVar: false, line: ' from ContingencyStatus'}
    - {isVar: false, line: ' where ID = ?'}
    name: SelectOne
    noRows: 0
    options: []
    orderFields: []
    outputs:
    - *id004
    - *id005
    - *id006
    placeHolders: []
    start: 18
    table: *id007
    updateFields: []
    useKey: false
    useStd: false
    username: ''
    where: ''
  - comments: []
    dynamicSizes: []
    dynamicStrung: []
    dynamics: []
    extendsStd: false
    fields: []
    from: ''
    hasImage: false
    hasReturning: false
    hasUpdates: false
    inputs: []
    isAction: false
    isData: true
    isIdlCode: false
    isInsert: false
    isMultipleInput: false
    isProc: false
    isSProc: false
    isSingle: false
    isSql: false
    isStd: false
    isUpdate: false
    lines:
    - {isVar: false, line: -- Takeons come here}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (0, ''PENDING'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (1, ''OPEN'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (2, ''SUSPENDED'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (3, ''CLOSED'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (4, ''FINALISED'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (5, ''RESULTED'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (6, ''PROVISIONAL_RESULT'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: 'INSERT INTO ContingencyStatus(id, description, usrid,
        tmstamp)VALUES (7, ''SETTLED'', ''SYSTEM'', CURRENT_TIMESTAMP);'}
    - {isVar: false, line: ''}
    name: ''
    noRows: 0
    options: []
    orderFields: []
    outputs: []
    placeHolders: []
    start: 0
    table: null
    updateFields: []
    useKey: false
    useStd: false
    username: ''
    where: ''
  start: 9
  views: []
userid: ''
views: []
```

**Comment by dieterrosch** [comment]
More examples attached.

[YamlOutput.zip](https://github.com/SI-Gen/jportal2/files/5480701/YamlOutput.zip)

**Review by testfile2 — APPROVED** [review]

**Review by VenoMpie — APPROVED** [review]

**Pull request merged**
